sudo: required
services:
  - docker
before_install:
  - docker pull ohiosupercomputer/docker-sphinx
script:
  - docker run --rm -i -t -v "${PWD}:/doc" -u "$(id -u):$(id -g)" ohiosupercomputer/docker-sphinx make html
after_success:
  - ./push.sh
notifications:
  email:
    on_success: never
    on_failure: always
